# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snapSetting_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator, QDoubleValidator


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 934)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(170, 850, 71, 16))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(40, 850, 71, 16))
        self.label_14.setObjectName("label_14")
        self.FrameSize = QtWidgets.QGroupBox(Form)
        self.FrameSize.setGeometry(QtCore.QRect(40, 220, 301, 141))
        self.FrameSize.setObjectName("FrameSize")
        self.startLeftCoordinate = QtWidgets.QLineEdit(self.FrameSize)
        self.startLeftCoordinate.setGeometry(QtCore.QRect(70, 30, 51, 20))
        self.startLeftCoordinate.setObjectName("startLeftCoordinate")
        self.startCoordinate = QtWidgets.QLabel(self.FrameSize)
        self.startCoordinate.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.startCoordinate.setObjectName("startCoordinate")
        self.interval1 = QtWidgets.QLabel(self.FrameSize)
        self.interval1.setGeometry(QtCore.QRect(130, 30, 21, 16))
        self.interval1.setObjectName("interval1")
        self.startRightCoordinate = QtWidgets.QLineEdit(self.FrameSize)
        self.startRightCoordinate.setGeometry(QtCore.QRect(150, 30, 51, 20))
        self.startRightCoordinate.setObjectName("startRightCoordinate")
        self.imageWidth = QtWidgets.QLineEdit(self.FrameSize)
        self.imageWidth.setGeometry(QtCore.QRect(70, 80, 51, 20))
        self.imageWidth.setObjectName("imageWidth")
        self.imageSize = QtWidgets.QLabel(self.FrameSize)
        self.imageSize.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.imageSize.setObjectName("imageSize")
        self.interval2 = QtWidgets.QLabel(self.FrameSize)
        self.interval2.setGeometry(QtCore.QRect(130, 80, 21, 16))
        self.interval2.setObjectName("interval2")
        self.imageHeight = QtWidgets.QLineEdit(self.FrameSize)
        self.imageHeight.setGeometry(QtCore.QRect(150, 80, 51, 20))
        self.imageHeight.setObjectName("imageHeight")
        self.YAxisRange = QtWidgets.QGroupBox(Form)
        self.YAxisRange.setGeometry(QtCore.QRect(40, 700, 301, 141))
        self.YAxisRange.setObjectName("YAxisRange")
        self.label_9 = QtWidgets.QLabel(self.YAxisRange)
        self.label_9.setGeometry(QtCore.QRect(30, 80, 51, 16))
        self.label_9.setObjectName("label_9")
        self.startPositionY = QtWidgets.QLineEdit(self.YAxisRange)
        self.startPositionY.setGeometry(QtCore.QRect(90, 30, 51, 20))
        self.startPositionY.setObjectName("startPositionY")
        self.label_12 = QtWidgets.QLabel(self.YAxisRange)
        self.label_12.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.YAxisRange)
        self.label_13.setGeometry(QtCore.QRect(150, 30, 21, 16))
        self.label_13.setObjectName("label_13")
        self.endPositionY = QtWidgets.QLineEdit(self.YAxisRange)
        self.endPositionY.setGeometry(QtCore.QRect(180, 30, 51, 20))
        self.endPositionY.setObjectName("endPositionY")
        self.stepLengthY = QtWidgets.QLineEdit(self.YAxisRange)
        self.stepLengthY.setGeometry(QtCore.QRect(90, 80, 51, 20))
        self.stepLengthY.setObjectName("stepLengthY")
        self.XAxisRange = QtWidgets.QGroupBox(Form)
        self.XAxisRange.setGeometry(QtCore.QRect(40, 540, 301, 141))
        self.XAxisRange.setObjectName("XAxisRange")
        self.label_7 = QtWidgets.QLabel(self.XAxisRange)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 51, 16))
        self.label_7.setObjectName("label_7")
        self.startPositionX = QtWidgets.QLineEdit(self.XAxisRange)
        self.startPositionX.setGeometry(QtCore.QRect(90, 30, 51, 20))
        self.startPositionX.setObjectName("startPositionX")
        self.label_10 = QtWidgets.QLabel(self.XAxisRange)
        self.label_10.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label_10.setObjectName("label_10")
        self.label1 = QtWidgets.QLabel(self.XAxisRange)
        self.label1.setGeometry(QtCore.QRect(150, 30, 21, 16))
        self.label1.setObjectName("label1")
        self.endPositionX = QtWidgets.QLineEdit(self.XAxisRange)
        self.endPositionX.setGeometry(QtCore.QRect(180, 30, 51, 20))
        self.endPositionX.setObjectName("endPositionX")
        self.stepLengthX = QtWidgets.QLineEdit(self.XAxisRange)
        self.stepLengthX.setGeometry(QtCore.QRect(90, 80, 51, 20))
        self.stepLengthX.setObjectName("stepLengthX")
        self.imageNum = QtWidgets.QLabel(Form)
        self.imageNum.setGeometry(QtCore.QRect(110, 850, 54, 12))
        self.imageNum.setObjectName("imageNum")
        self.ImageSave = QtWidgets.QGroupBox(Form)
        self.ImageSave.setGeometry(QtCore.QRect(40, 390, 301, 141))
        self.ImageSave.setObjectName("ImageSave")
        self.originPath = QtWidgets.QLineEdit(self.ImageSave)
        self.originPath.setGeometry(QtCore.QRect(100, 30, 111, 20))
        self.originPath.setObjectName("originPath")
        self.originLabel = QtWidgets.QLabel(self.ImageSave)
        self.originLabel.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.originLabel.setObjectName("originLabel")
        self.predictPath = QtWidgets.QLineEdit(self.ImageSave)
        self.predictPath.setGeometry(QtCore.QRect(100, 70, 111, 20))
        self.predictPath.setObjectName("predictPath")
        self.predictLabel = QtWidgets.QLabel(self.ImageSave)
        self.predictLabel.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.predictLabel.setObjectName("predictLabel")
        self.originPathSelect = QtWidgets.QPushButton(self.ImageSave)
        self.originPathSelect.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.originPathSelect.setObjectName("originPathSelect")
        self.predictPathSelect = QtWidgets.QPushButton(self.ImageSave)
        self.predictPathSelect.setGeometry(QtCore.QRect(220, 70, 75, 23))
        self.predictPathSelect.setObjectName("predictPathSelect")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(210, 910, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Exposure = QtWidgets.QGroupBox(Form)
        self.Exposure.setGeometry(QtCore.QRect(40, 30, 301, 141))
        self.Exposure.setObjectName("Exposure")
        self.HandExposure = QtWidgets.QRadioButton(self.Exposure)
        self.HandExposure.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.HandExposure.setObjectName("HandExposure")
        self.AutoExposure = QtWidgets.QRadioButton(self.Exposure)
        self.AutoExposure.setGeometry(QtCore.QRect(90, 40, 89, 16))
        self.AutoExposure.setObjectName("AutoExposure")
        self.ExposureType = QtWidgets.QLineEdit(self.Exposure)
        self.ExposureType.setGeometry(QtCore.QRect(10, 80, 51, 20))
        self.ExposureType.setObjectName("ExposureType")
        self.ExposureUit = QtWidgets.QLabel(self.Exposure)
        self.ExposureUit.setGeometry(QtCore.QRect(70, 80, 21, 16))
        self.ExposureUit.setObjectName("ExposureUit")
        self.ExposureSlider = QtWidgets.QSlider(self.Exposure)
        self.ExposureSlider.setGeometry(QtCore.QRect(90, 80, 201, 22))
        self.ExposureSlider.setMinimum(1)
        self.ExposureSlider.setMaximum(1000)
        self.ExposureSlider.setProperty("value", 1)
        self.ExposureSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ExposureSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.ExposureSlider.setTickInterval(1)
        self.ExposureSlider.setObjectName("ExposureSlider")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_15.setText(_translate("Form", "辐结果"))
        self.label_14.setText(_translate("Form", "总计要输出"))
        self.FrameSize.setTitle(_translate("Form", "视域"))
        self.startCoordinate.setText(_translate("Form", "起始坐标"))
        self.interval1.setText(_translate("Form", "/"))
        self.imageSize.setText(_translate("Form", "图像尺寸"))
        self.interval2.setText(_translate("Form", "x"))
        self.YAxisRange.setTitle(_translate("Form", "y轴范围"))
        self.label_9.setText(_translate("Form", "步长"))
        self.startPositionY.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "范围"))
        self.label_13.setText(_translate("Form", "……"))
        self.endPositionY.setText(_translate("Form", "1000"))
        self.stepLengthY.setText(_translate("Form", "100"))
        self.XAxisRange.setTitle(_translate("Form", "x轴范围"))
        self.label_7.setText(_translate("Form", "步长"))
        self.startPositionX.setText(_translate("Form", "0"))
        self.label_10.setText(_translate("Form", "范围"))
        self.label1.setText(_translate("Form", "……"))
        self.endPositionX.setText(_translate("Form", "1000"))
        self.stepLengthX.setText(_translate("Form", "100"))
        self.imageNum.setText(_translate("Form", "100"))
        self.ImageSave.setTitle(_translate("Form", "保存路径"))
        self.originLabel.setText(_translate("Form", "原图保存路径"))
        self.predictLabel.setText(_translate("Form", "预测图保存路径"))
        self.originPathSelect.setText(_translate("Form", "重新选择"))
        self.predictPathSelect.setText(_translate("Form", "重新选择"))
        self.Exposure.setTitle(_translate("Form", "曝光时间"))
        self.HandExposure.setText(_translate("Form", "手动曝光"))
        self.AutoExposure.setText(_translate("Form", "自动曝光"))
        self.ExposureUit.setText(_translate("Form", "ms"))

        intValidator = QIntValidator(-30000,50000)
        doubleValidator = QDoubleValidator(0,1000,1)
        self.ExposureType.setValidator(doubleValidator)
        self.startPositionX.setValidator(intValidator)
        self.startPositionY.setValidator(intValidator)
        self.endPositionX.setValidator(intValidator)
        self.endPositionY.setValidator(intValidator)
        self.stepLengthX.setValidator(intValidator)
        self.stepLengthY.setValidator(intValidator)



        self.ExposureSlider.valueChanged.connect(self.sliderToText)
        self.ExposureType.textChanged.connect(self.textToSlider)
        self.HandExposure.toggled.connect(self.radioButtonChanged)

        self.originPathSelect.clicked.connect(self.selectOriginPath)
        self.predictPathSelect.clicked.connect(self.selectPredictPath)

        self.startPositionX.textChanged.connect(self.getResultNum)
        self.endPositionX.textChanged.connect(self.getResultNum)
        self.startPositionY.textChanged.connect(self.getResultNum)
        self.endPositionY.textChanged.connect(self.getResultNum)
        self.stepLengthX.textChanged.connect(self.getResultNum)
        self.stepLengthY.textChanged.connect(self.getResultNum)




    def sliderToText(self):
        self.ExposureType.setText(str(self.ExposureSlider.value()))

    def textToSlider(self):
        if self.ExposureType.text() == "":
            return
        self.ExposureSlider.setValue(int(self.ExposureType.text().split('.')[0]))

    def radioButtonChanged(self):
        if self.HandExposure.isChecked():
            self.ExposureType.setEnabled(True)
            self.ExposureSlider.setEnabled(True)
        else:
            self.ExposureType.setEnabled(False)
            self.ExposureSlider.setEnabled(False)

    def selectOriginPath(self):
        dir = QtWidgets.QFileDialog.getExistingDirectory()
        self.originPath.setText(dir)
        return

    def selectPredictPath(self):
        dir = QtWidgets.QFileDialog.getExistingDirectory()
        self.predictPath.setText(dir)
        return

    def getResultNum(self):
        startX = int(self.startPositionX.text())
        endX = int(self.endPositionX.text())
        stepX = int(self.stepLengthX.text())
        startY = int(self.startPositionY.text())
        endY = int(self.endPositionY.text())
        stepY = int(self.stepLengthY.text())
        numX = (endX - startX + stepX - 1) // stepX
        numY = (endY - startY + stepY - 1) // stepY
        numImage = numY * numX
        self.imageNum.setText(str(numImage))
