# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from UI import submainwindow, step4_menu
from PyQt5.QtCore import pyqtSlot
import sys

class BigMainWindow(object):
    def __init__(self,parent=None):
        self.parent = parent

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(846, 467)
        self.step1 = QtWidgets.QPushButton(Form)
        self.step1.setGeometry(QtCore.QRect(140, 180, 111, 71))
        self.step1.setObjectName("step1")
        self.step2_3 = QtWidgets.QPushButton(Form)
        self.step2_3.setGeometry(QtCore.QRect(340, 180, 111, 71))
        self.step2_3.setObjectName("step2_3")
        self.step4 = QtWidgets.QPushButton(Form)
        self.step4.setGeometry(QtCore.QRect(540, 180, 111, 71))
        self.step4.setObjectName("step4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.subMainwindw2_3 = submainwindow.SubMainWindow()
        # self.app = QtWidgets.QApplication(sys.argv)
        # self.mainwindow = QtWidgets.QMainWindow(self)
        self.mainwindow = QtWidgets.QMainWindow()
        self.subMainwindw2_3.setupUi(self.mainwindow)
        self.menuWindwo4 = QtWidgets.QMainWindow()
        self.subMainwindow4 = step4_menu.Ui_MainWindow(self.parent)
        self.subMainwindow4.setupUi(self.menuWindwo4)

        self.step2_3.clicked.connect(self.showSmallMainwindow2_3)
        self.step4.clicked.connect(self.showStepMenu4)
        self.subMainwindow4.exit.triggered.connect(self.closeSubWindow)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.step1.setText(_translate("Form", "原始物料分析"))
        self.step2_3.setText(_translate("Form", "矿相分析"))
        self.step4.setText(_translate("Form", "孔隙分析"))


    # @pyqtSlot()
    def showSmallMainwindow2_3(self):
        self.parent.hide()
        self.mainwindow.show()

    def showStepMenu4(self):
        self.parent.hide()
        self.menuWindwo4.show()

    def closeSubWindow(self):
        self.parent.setHidden(False)