# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 353)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 60, 54, 12))
        self.label.setObjectName("label")
        self.time = QtWidgets.QLineEdit(Form)
        self.time.setGeometry(QtCore.QRect(160, 55, 141, 20))
        self.time.setObjectName("time")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 115, 54, 12))
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(160, 110, 141, 20))
        self.name.setObjectName("name")
        self.number = QtWidgets.QLineEdit(Form)
        self.number.setGeometry(QtCore.QRect(160, 165, 141, 20))
        self.number.setObjectName("number")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 170, 54, 12))
        self.label_3.setObjectName("label_3")
        self.source = QtWidgets.QLineEdit(Form)
        self.source.setGeometry(QtCore.QRect(160, 225, 141, 20))
        self.source.setText("")
        self.source.setObjectName("source")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 54, 12))
        self.label_4.setObjectName("label_4")
        self.query = QtWidgets.QPushButton(Form)
        self.query.setGeometry(QtCore.QRect(400, 60, 75, 23))
        self.query.setObjectName("query")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(400, 110, 75, 23))
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "试验时间"))
        self.label_2.setText(_translate("Form", "试验名称"))
        self.label_3.setText(_translate("Form", "试样编号"))
        self.label_4.setText(_translate("Form", "试样来源"))
        self.query.setText(_translate("Form", "查询"))
        self.exit.setText(_translate("Form", "关闭"))
