# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step2_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.parameter_setting = QtWidgets.QAction(MainWindow)
        self.parameter_setting.setObjectName("parameter_setting")
        self.real_time_setting = QtWidgets.QAction(MainWindow)
        self.real_time_setting.setObjectName("real_time_setting")
        self.auto_analysis = QtWidgets.QAction(MainWindow)
        self.auto_analysis.setObjectName("auto_analysis")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.open_report = QtWidgets.QAction(MainWindow)
        self.open_report.setObjectName("open_report")
        self.modify_report = QtWidgets.QAction(MainWindow)
        self.modify_report.setObjectName("modify_report")
        self.save_report = QtWidgets.QAction(MainWindow)
        self.save_report.setObjectName("save_report")
        self.print_report = QtWidgets.QAction(MainWindow)
        self.print_report.setObjectName("print_report")
        self.query_report = QtWidgets.QAction(MainWindow)
        self.query_report.setObjectName("query_report")
        self.open_excel = QtWidgets.QAction(MainWindow)
        self.open_excel.setObjectName("open_excel")
        self.offline_analysis = QtWidgets.QAction(MainWindow)
        self.offline_analysis.setObjectName("offline_analysis")
        self.menu.addAction(self.parameter_setting)
        self.menu.addAction(self.real_time_setting)
        self.menu.addAction(self.auto_analysis)
        self.menu.addAction(self.exit)
        self.menu_2.addAction(self.open_report)
        self.menu_2.addAction(self.modify_report)
        self.menu_2.addAction(self.save_report)
        self.menu_2.addAction(self.print_report)
        self.menu_2.addAction(self.query_report)
        self.menu_3.addAction(self.open_excel)
        self.menu_4.addAction(self.offline_analysis)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "操作"))
        self.menu_2.setTitle(_translate("MainWindow", "试验报告"))
        self.menu_3.setTitle(_translate("MainWindow", "试验数据"))
        self.menu_4.setTitle(_translate("MainWindow", "方式"))
        self.parameter_setting.setText(_translate("MainWindow", "参数设置"))
        self.real_time_setting.setText(_translate("MainWindow", "实时显示"))
        self.auto_analysis.setText(_translate("MainWindow", "自动分析"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.open_report.setText(_translate("MainWindow", "打开文件"))
        self.modify_report.setText(_translate("MainWindow", "修改报告"))
        self.save_report.setText(_translate("MainWindow", "保存"))
        self.print_report.setText(_translate("MainWindow", "打印"))
        self.query_report.setText(_translate("MainWindow", "历史报告查询"))
        self.open_excel.setText(_translate("MainWindow", "打开Excel"))
        self.offline_analysis.setText(_translate("MainWindow", "离线分析"))
