# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UI import step2_menu, step3_menu


class SubMainWindow(object):
    def __init__(self,parent = None):
        self.parent = parent

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 337)
        self.step2 = QtWidgets.QPushButton(Form)
        self.step2.setGeometry(QtCore.QRect(80, 110, 111, 71))
        self.step2.setObjectName("step2")
        self.step3 = QtWidgets.QPushButton(Form)
        self.step3.setGeometry(QtCore.QRect(280, 110, 111, 71))
        self.step3.setObjectName("step3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.menuStep2 = QtWidgets.QMainWindow()
        self.step2Window = step2_menu.Ui_MainWindow()
        self.step2Window.setupUi(self.menuStep2)

        self.menuStep3 = QtWidgets.QMainWindow()
        self.step3Window = step3_menu.Ui_MainWindow()
        self.step3Window.setupUi(self.menuStep3)

        self.step2.clicked.connect(self.showStep2Menu)
        self.step3.clicked.connect(self.showStep3Menu)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.step2.setText(_translate("Form", "矿物组成分析"))
        self.step3.setText(_translate("Form", "矿物尺寸分析"))

    def showStep2Menu(self):
        self.menuStep2.show()

    def showStep3Menu(self):
        self.menuStep3.show()