# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from UI import subMainWindow, step4_menu


class BigMainWindow(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(BigMainWindow, self).__init__(parent)
        self.setBaseSize(846, 467)
        self.step1 = QtWidgets.QPushButton(self)
        self.step1.setGeometry(QtCore.QRect(140, 180, 111, 71))
        self.step2_3 = QtWidgets.QPushButton(self)
        self.step2_3.setGeometry(QtCore.QRect(340, 180, 111, 71))
        self.step4 = QtWidgets.QPushButton(self)
        self.step4.setGeometry(QtCore.QRect(540, 180, 111, 71))

        self.step2_3.clicked.connect(self.showSmallMainwindow2_3)
        self.step4.clicked.connect(self.showSmallMainwindow4)
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.step1.setText(_translate("Form", "原始物料分析"))
        self.step2_3.setText(_translate("Form", "矿相分析"))
        self.step4.setText(_translate("Form", "孔隙分析"))

    def showSmallMainwindow2_3(self):
        try:
            self.window2_3 = subMainWindow.SubMainWindow(subParent=self)
            self.hide()
            self.window2_3.show()
        except Exception as e:
            print(e)

    def showSmallMainwindow4(self):
        try:
            QtWidgets.QMessageBox.warning(self, '提示', '请确认物镜为 5X 物镜')
            self.window4 = step4_menu.Step4Menu(subParent=self)
            self.hide()
            self.window4.show()
            self.window4.showGlobalSetting()
        except Exception as e:
            print(e)
