# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step2_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import win32com.client as win32
from pathlib import Path

from PyQt5 import QtCore, QtGui, QtWidgets
from UI import query_report, global_setting
from Core import Camera
import cv2 as cv
from skimage.measure import label
from Core.neuralNet import predict
import numpy as np
import datetime


class Step3Menu(QtWidgets.QMainWindow):
    def __init__(self, parent=None, subParent=None):
        self.parent = subParent
        super(Step3Menu, self).__init__(parent)
        self.setObjectName("Form")
        self.resize(1123, 741)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.parameter_setting = QtWidgets.QAction(self)
        self.parameter_setting.setObjectName("parameter_setting")
        self.real_time_setting = QtWidgets.QAction(self)
        self.real_time_setting.setObjectName("real_time_setting")
        self.auto_analysis = QtWidgets.QAction(self)
        self.auto_analysis.setObjectName("auto_analysis")
        self.handExit = QtWidgets.QAction(self)
        self.handExit.setObjectName("handExit")
        self.open_report = QtWidgets.QAction(self)
        self.open_report.setObjectName("open_report")
        self.modify_report = QtWidgets.QAction(self)
        self.modify_report.setObjectName("modify_report")
        self.save_report = QtWidgets.QAction(self)
        self.save_report.setObjectName("save_report")
        self.print_report = QtWidgets.QAction(self)
        self.print_report.setObjectName("print_report")
        self.query_report = QtWidgets.QAction(self)
        self.query_report.setObjectName("query_report")
        self.open_excel = QtWidgets.QAction(self)
        self.open_excel.setObjectName("open_excel")
        self.offline_analysis = QtWidgets.QAction(self)
        self.offline_analysis.setObjectName("offline_analysis")
        self.menu.addAction(self.parameter_setting)
        self.menu.addAction(self.real_time_setting)
        self.menu.addAction(self.auto_analysis)
        self.menu.addAction(self.handExit)
        self.menu_2.addAction(self.open_report)
        self.menu_2.addAction(self.modify_report)
        self.menu_2.addAction(self.save_report)
        self.menu_2.addAction(self.print_report)
        self.menu_2.addAction(self.query_report)
        self.menu_3.addAction(self.open_excel)
        self.menu_4.addAction(self.offline_analysis)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.queryReport = None
        self.globalSetting = None
        # self.camera = Camera.Camera()
        self.imageNum = 0
        self.startCoordinateX = 0
        self.startCoordinateY = 0
        self.endCoordinateX = 0
        self.endCoordinateY = 0
        self.stepLengthX = 1
        self.stepLengthY = 1
        self.predict = None
        self.query_report.triggered.connect(self.showQueryReport)
        self.parameter_setting.triggered.connect(self.showGlobalSetting)
        self.open_report.triggered.connect(self.openFile)
        self.handExit.triggered.connect(self.handClose)
        self.open_excel.triggered.connect(self.openExcel)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.camera = Camera.Camera()
        self.analysisPramter()

    def analysisPramter(self):
        """载物台"""
        self.startX = 0
        self.endX = 1
        self.startY = 0
        self.endY = 1
        self.stepLengthX = 1
        self.stepLengthY = 1

        """保存路径"""
        self.isSaveImage = False
        self.originImageSaveDir = ""
        self.preidctImageSaveDir = ""
        self.offlineSaveReportDir = ""
        self.onlineSaveReportDir = ""

        """报告所需参数"""
        self.className = ['矿1', '矿2', '矿3', '矿4', '矿5', '矿6', '矿7', '矿8','矿9']
        self.pie = True
        self.page = ['', '']
        self.header = ['', '']
        self.testParmter = ['', '', '', '', '', '', '', '']
        self.startTime = ''
        self.endTime = ''

        """摄像头"""
        self.frameLeft = 176
        self.frameTop = 204
        self.frameWidth = 2400
        self.frameHeight = 1800
        self.autoExposure = False
        self.exposureTime = 30.0
        self.whiteBalanceRed = 120
        self.whiteBalanceGreen = 120
        self.whiteBalanceBlue = 120
        self.colorTemperature = 50

        """类别代表颜色"""
        self.classColor = [
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0]
        ]

        self.camera = Camera.Camera()
        self.chkpth = "File/config/step2_3.pth"
        self.n_class = 9
        self.stepLength = 1
        self.Predict = predict.Predict(chkpth=self.chkpth, n_classes=self.n_class)
        self.imgPath = b"File/config/step4.pth"
        self.classArea = [10, 30, 50, 100, 200, 300, 500, 700, 1000, 1200, 1500, 1700, 2000]
        for i in range(0, len(self.classArea)):
            self.classArea[i] = int(pow(self.classArea[i] / 2, 2) * 3.14)
        self.classAreaSum = [
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        ]
        self.classProportition = []

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "step3"))
        self.menu.setTitle(_translate("self", "操作"))
        self.menu_2.setTitle(_translate("self", "试验报告"))
        self.menu_3.setTitle(_translate("self", "试验数据"))
        self.menu_4.setTitle(_translate("self", "方式"))
        self.parameter_setting.setText(_translate("self", "参数设置"))
        self.real_time_setting.setText(_translate("self", "实时显示"))
        self.auto_analysis.setText(_translate("self", "自动分析"))
        self.handExit.setText(_translate("self", "退出"))
        self.open_report.setText(_translate("self", "打开文件"))
        self.modify_report.setText(_translate("self", "修改报告"))
        self.save_report.setText(_translate("self", "保存"))
        self.print_report.setText(_translate("self", "打印"))
        self.query_report.setText(_translate("self", "历史报告查询"))
        self.open_excel.setText(_translate("self", "打开Excel"))
        self.offline_analysis.setText(_translate("self", "离线分析"))

    def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
        a0.accept()
        self.parent.setVisible(True)

    def showQueryReport(self):
        self.queryReport = query_report.QueryReport()
        self.queryReport.show()

    def showGlobalSetting(self):
        self.globalSetting = global_setting.GlobalSetting(subParent=self, idx=3)
        self.globalSetting.show()

    def openFile(self):
        fileName = QtWidgets.QFileDialog.getOpenFileName()
        print(fileName)

    def handClose(self):
        self.setVisible(False)
        self.parent.setVisible(True)

    def openExcel(self):
        '''

        :return:
        '''
        fileName = QtWidgets.QFileDialog.getOpenFileName()
        if fileName[0] != '':
            out_file = Path.cwd() / fileName[0]
            excel = win32.gencache.EnsureDispatch('Excel.Application')
            excel.Visible = True
            excel.Workbooks.Open(out_file)

    def autoAnalysis(self):
        self.startTime = datetime.datetime.now().strftime("%Y.%m.%d %H:%M")
        direction = True
        curPositionX = 0
        imageIdx = 0
        for row in range(self.startY, self.endY, self.stepLengthY):
            if direction:
                for col in range(self.startX, self.endX, self.stepLengthX):
                    curPositionX = col
                    if self.isSaveImage:
                        self.imagePath = (self.originImageSaveDir + '/' + str(imageIdx) + '.png').encode(
                            encoding='utf-8')
                    else:
                        self.imagePath = b'a.png'
                    self.camera.stage.setPosition(row, col)
                    self.camera.BinaryAutoFocus()
                    self.camera.WriteImage(imagePath=self.imagePath)
                    self.analyseImage()
                    imageIdx += 1
                direction = False
            else:
                for col in range(curPositionX, self.startX - 1, -self.stepLengthX):
                    curPositionX = col
                    if self.isSaveImage:
                        self.imagePath = (self.originImageSaveDir + '/' + str(imageIdx) + '.png').encode(
                            encoding='utf-8')
                    else:
                        self.imagePath = 'a.png'
                    self.camera.stage.setPosition(row, col)
                    self.camera.BinaryAutoFocus()
                    self.camera.WriteImage(imagePath=self.imagePath)
                    self.analyseImage()
                    imageIdx += 1
                direction = True
        self.endTime = datetime.datetime.now().strftime("%Y.%m.%d %H:%M")
        self.testParmter[1] = self.startTime + '-' + self.endTime[-5:]
        self.testParmter[5] = "自动分析方式"
        self.testParmter[6] = str(imageIdx)

    def analyseImage(self):
        '''
        analyseize image
        :return:
        '''
        img = cv.imread(self.imgPath)
        mark = self.Predict.predict(image=img, stepLength=self.stepLength)
        if self.isSaveImage:
            colorMark = np.zeros((mark.shape[0], mark.shape[1], 3))
            for i in range(0, self.n_class):
                colorMark[mark == i] = self.classColor[i]
            cv.imwrite(self.preidctImageSaveDir + '/' + self.imagePath.split('/')[-1], colorMark)
        mark[mark == 3] = 2
        mark[(mark == 4) | (mark == 5)] = 3
        mark[(mark == 6) | (mark == 7)] = 4
        mark[mark == 8] = 5
        indexImg = np.zeros((img.shape[0], img.shape[1]))
        for i in range(0, 6):
            indexImg[:, :] = 0
            indexImg[mark == i] = 1
            labels, num = label(indexImg, background=0, return_num=True, connectivity=2)
            for j in range(1, num + 1):
                singleArea = len(np.where(labels == i)[0])
                for j in range(0, len(self.classArea)):
                    if singleArea < self.classAreaSum[j]:
                        self.classAreaSum[i][j] += singleArea
                        break
