# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step4_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 893)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(0, 80, 1281, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.selectImage = QtWidgets.QPushButton(Form)
        self.selectImage.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.selectImage.setObjectName("selectImage")
        self.analyse = QtWidgets.QPushButton(Form)
        self.analyse.setGeometry(QtCore.QRect(190, 30, 101, 41))
        self.analyse.setObjectName("analyse")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectImage.setText(_translate("Form", "选择图片"))
        self.analyse.setText(_translate("Form", "分析"))
